"""Regression vectors for the stock client's LZF wire framing."""

from protocol.runtime_packets import decode_set_class_loadout_payload
from server.util import lzf_decompress


# Generated by the retail 32-bit shared.lzf.pyd from a real Engineer packet-13
# body.  It contains overlapping back-references across all three prefab names.
_RETAIL_THREE_PREFAB_PACKET = bytes.fromhex(
    "1f0dff0c000c0500073a40171e191a1e1617037072656661625f63616c74726f70"
    "0000a00e097375706572746f776572c0110075201f0961626172726965720000"
)


def test_retail_lzf_backreferences_preserve_all_three_prefab_strings():
    """Stock LZF back-references must use the encoded distance plus one."""

    decoded = lzf_decompress(_RETAIL_THREE_PREFAB_PACKET)
    packet = decode_set_class_loadout_payload(decoded[1:])

    assert packet.prefabs == [
        "prefab_caltrop",
        "prefab_supertower",
        "prefab_ultrabarrier",
    ]

