"""Regenerate the server's stock-map sidecars from the retail client install.

Retail sources this tool reads (never executes):

* ``maps/<Map>.txtc`` -- compiled Python 2.7 map-description modules. Retail
  shipped them for DragonIsland, MayanJungle, SpookyMansion and Trenches
  only; the other stock maps' descriptions lived on the retail server and were
  never distributed.  Every assignment is copied verbatim into
  ``maps/<Map>.json`` (tuples become JSON lists) so the server parser sees the
  complete retail layout: spawn areas, team bases, per-mode spawn overrides,
  CTF/TC/MH/Diamond/Occupation objectives, crates, lighting, fog, ambience and
  ground palette.
* ``aos.pkg`` -> ``playlists.mapinfo`` -- the retail map catalogue (per-map
  invalid modes, player caps, classic/demo/mafia flags).
* ``playlists/*.txt`` -- retail official rotations (which maps each mode's
  playlist actually served).

The last two are merged into ``maps/retail_map_info.json``.

Usage::

    py -3.12 tools/map_metadata/extract_retail.py            # write
    py -3.12 tools/map_metadata/extract_retail.py --check    # verify in sync

``--client-root`` may be repeated; the first root holding a given file wins.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.map_metadata.py27 import (  # noqa: E402
    load_archive_module,
    load_pyc,
    evaluate_module,
)

DEFAULT_CLIENT_ROOTS = (
    Path(r"C:\Program Files (x86)\Steam\steamapps\common\aceofspades"),
    ROOT.parent / "aceofspades_nonsteam",
    ROOT.parent / "aceofspades_source",
)

# The protocol mode codes retail's map catalogue reasons about.
RETAIL_MODES = ("ctf", "tdm", "dem", "dia", "mh", "oc", "tc", "vip", "zom", "tut", "ugc")

MAP_INFO_NAME = "retail_map_info.json"


def _jsonable(value):
    if isinstance(value, (tuple, list)):
        return [_jsonable(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, (frozenset, set)):
        return sorted(_jsonable(item) for item in value)
    if isinstance(value, bytes):
        return value.decode("latin-1")
    return value


def _find(roots: list[Path], relative: str) -> Path | None:
    for root in roots:
        candidate = root / relative
        if candidate.is_file():
            return candidate
    return None


def retail_sidecar(txtc: Path) -> dict[str, object]:
    """Return the JSON sidecar payload for one retail ``.txtc`` module."""

    code = load_pyc(txtc)
    payload = {key: _jsonable(value) for key, value in evaluate_module(code).items()}
    payload["_retail_source"] = {
        "file": txtc.name,
        "sha256": hashlib.sha256(txtc.read_bytes()).hexdigest(),
        "compiled_from": code.filename.replace("\\", "/"),
        "note": "generated by tools/map_metadata/extract_retail.py; do not hand-edit",
    }
    return payload


def retail_map_info(package: Path, playlists_dir: Path | None) -> dict[str, object]:
    """Merge retail ``playlists.mapinfo`` with the shipped official playlists."""

    catalogue = load_archive_module(package, "playlists.mapinfo")["map_info"]
    playlists: dict[str, dict[str, object]] = {}
    if playlists_dir is not None and playlists_dir.is_dir():
        for path in sorted(playlists_dir.glob("*.txt")):
            try:
                playlist = ast.literal_eval(path.read_text(encoding="utf-8"))
            except (OSError, ValueError, SyntaxError):
                continue
            if isinstance(playlist, dict):
                playlists[path.stem] = {
                    "modes": list(playlist.get("modes", ())),
                    "maps": list(playlist.get("maps", ())),
                    "classic": bool(playlist.get("classic", False)),
                    "mafia": bool(playlist.get("mafia", False)),
                    "players": [int(v) for v in playlist.get("players", ()) or ()],
                    "config": dict(playlist.get("config", {}) or {}),
                }

    maps: dict[str, object] = {}
    for name in sorted(catalogue, key=str.casefold):
        entry = catalogue[name]
        invalid = [str(mode) for mode in entry.get("invalid_modes", ())]
        # Retail ``playlists.PlayList.__init__`` builds every playlist as
        # mode x map pairs and SKIPS a pair when the mode is in the map's
        # ``invalid_modes``, the map's classic/mafia flag differs from the
        # playlist's, or the map is not ``release``.  So although the raw
        # demolition.txt lists GreatWall and occupation.txt BranCastle,
        # retail never served either pair.
        playlist_modes = sorted({
            str(mode)
            for playlist in playlists.values()
            if name in playlist["maps"]
            for mode in playlist["modes"]
            if str(mode) not in invalid
            and bool(playlist["classic"]) == bool(entry.get("classic", False))
            and bool(playlist["mafia"]) == bool(entry.get("mafia", False))
            and bool(entry.get("release", False))
        })
        maps[name] = {
            "valid_modes": [mode for mode in RETAIL_MODES if mode not in invalid],
            "invalid_modes": invalid,
            "playlist_modes": playlist_modes,
            "max_players": int(entry.get("max_players", 32)),
            "classic": bool(entry.get("classic", False)),
            "demo": bool(entry.get("demo", False)),
            "mafia": bool(entry.get("mafia", False)),
            "release": bool(entry.get("release", False)),
        }
    return {
        "_retail_source": {
            "catalogue": "aos.pkg:playlists.mapinfo",
            "catalogue_sha256": hashlib.sha256(package.read_bytes()).hexdigest(),
            "playlists": "playlists/*.txt",
            "note": "generated by tools/map_metadata/extract_retail.py; do not hand-edit",
        },
        "maps": maps,
        "playlists": playlists,
    }


def _dump(payload: dict[str, object], indent: str = "") -> str:
    """One key per line with compact values: diffable and still small."""

    inner = indent + "  "
    lines = []
    for key, value in payload.items():
        if isinstance(value, dict) and value and all(
            isinstance(item, dict) for item in value.values()
        ):
            text = _dump(value, inner).rstrip("\n")
        else:
            text = json.dumps(value, ensure_ascii=False, separators=(", ", ": "))
        lines.append(f"{inner}{json.dumps(key)}: {text}")
    body = ",\n".join(lines)
    return "{\n" + body + "\n" + indent + "}" + ("\n" if not indent else "")


def build_outputs(roots: list[Path], maps_dir: Path) -> dict[Path, str]:
    """Return ``{output path: text}`` for every recoverable retail artefact."""

    outputs: dict[Path, str] = {}
    txtc_files: dict[str, Path] = {}
    for root in [*roots, maps_dir.parent]:
        for path in sorted((root / "maps").glob("*.txtc")):
            txtc_files.setdefault(path.stem.casefold(), path)
    for path in txtc_files.values():
        outputs[maps_dir / f"{path.stem}.json"] = _dump(retail_sidecar(path))

    package = _find(roots, "aos.pkg")
    if package is not None:
        playlists = _find(roots, "playlists/ctf.txt")
        outputs[maps_dir / MAP_INFO_NAME] = _dump(
            retail_map_info(package, playlists.parent if playlists else None)
        )
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--client-root", action="append", type=Path, default=None)
    parser.add_argument("--maps-dir", type=Path, default=ROOT / "maps")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when a committed sidecar differs from retail")
    args = parser.parse_args(argv)

    roots = [root for root in (args.client_root or DEFAULT_CLIENT_ROOTS) if root.is_dir()]
    outputs = build_outputs(roots, args.maps_dir)
    if not outputs:
        print("no retail sources found; pass --client-root", file=sys.stderr)
        return 2

    stale = 0
    for path, text in sorted(outputs.items()):
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == text:
            print(f"up to date  {path.name}")
            continue
        stale += 1
        if args.check:
            print(f"STALE       {path.name}")
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote       {path.name}")
    return 1 if (args.check and stale) else 0


if __name__ == "__main__":
    raise SystemExit(main())
